<?
	$SESSAO_CODIGO = $_SESSION['SESSAO_CODIGO'];
	$SESSAO_NOME = $_SESSION['SESSAO_NOME'];
	$SESSAO_SNOME = $_SESSION['SESSAO_SNOME'];
	$SESSAO_LOGIN = $_SESSION['SESSAO_LOGIN'];
	$SESSAO_EMAIL = $_SESSION['SESSAO_EMAIL'];
	$SESSAO_DATACADASTRO = $_SESSION['SESSAO_DATACADASTRO'];
	$SESSAO_DATAALTCADASTRO = $_SESSION['SESSAO_DATAALTCADASTRO'];
?>